### ISSUE TITLE
Finish SVG icon

### ISSUE THREAD

**Issue by nii236** [nodeschool/perth#1]
The logo is almost finished! Just need that extra little push :+1:

**Comment by nii236** [comment]
@miqid: What do you think of these changes?

![](http://puu.sh/kNeBd/e44e25a6c0.png)

**Comment by ghost** [comment]
@nii236, I don't think we should can the buildings because it is a _school_ after all.

An alternative for you to consider below (cf. 0b77f11)

![ns-logo-alt](https://cloud.githubusercontent.com/assets/2031402/10562130/ffc82290-757d-11e5-89a6-0395e0204669.png)

**Comment by nii236** [comment]
I had a look at a bunch of other chapters and a lot of them seem to just use the generic building logo hmm...

There is actually a coloured one here, interesting... ![](http://nodeschool.io/sanfrancisco/assets/logo.png)

**Comment by nii236** [comment]
@miqid Go ahead and submit a PR for that logo you posted, that one will be a good compromise.
1. One with the yellow/black colourscheme (for making stickers)
2. One with the standard colours to put on the website

Also consider removing the eyes in that swan, dunno if it'll look better or not.
