### ISSUE TITLE
Public site directory contains superfluous files

### ISSUE THREAD

**Issue by ghost** [nodeschool/perth#6]
I noticed some directories and files that don't appear to be used whatsoever by the public site (i.e. `/img`, `/share`, possibly more) are being kept around.

@nii236, could you delete everything in the `public` folder and try generate the site once more?

**Comment by nii236** [comment]
Yeah done :+1:

**Comment by ghost** [comment]
@nii236, reopening this - I still see files which aren't being used (aforementioned folders above) hanging around.

**Comment by nii236** [comment]
@miqid: This is expected behaviour. It merges from the [Hugo Base Theme](https://github.com/crakjie/hugo-base-theme), which have these assets in the `static` folder. The only way to remove said files is to modify the base theme itself, which is not recommended.
